const bookTitles = [
  "Shadow of the Wind",
  "The Silent Forest",
  "Crimson Skies",
  "Golden Horizon",
  "Whispers in Time",
  "The Last Kingdom",
  "Echoes of Tomorrow",
  "Hidden Truths",
  "Moonlit Path",
  "The Iron Gate",
  "Broken Symphony",
  "Velvet Storm",
  "Burning Ashes",
  "Frozen Memories",
  "Fading Light",
  "Lost Empire",
  "Secret Garden",
  "Storm Riders",
  "Crystal River",
  "Midnight Library",
  "Dark Horizons",
  "Silver Flames",
  "Silent Thunder",
  "The Fallen Crown",
  "Emerald Sea",
  "Ancient Code",
  "The Glass Tower",
  "Wild Frontier",
  "Scarlet Promise",
  "Lonely Planet",
  "Hidden Valley",
  "Endless Night",
  "The Blue Phoenix",
  "Shattered Dreams",
  "Golden Compass",
  "Silver Arrow",
  "Lost in Shadows",
  "The Ruby Key",
  "Winter Sun",
  "Ocean of Stars",
  "Forgotten Tales",
  "Dust and Glory",
  "Iron Shadows",
  "Celestial Fire",
  "Broken Compass",
  "The Ivory Throne",
  "Shadow Hunter",
  "The Last Voyage",
  "Whispering Pines",
  "Dragon’s Call",
  "Silent Harbor",
  "Frozen Crown",
  "Hidden Blade",
  "Midnight Storm",
  "Golden Empire",
  "Secret Passage",
  "The Dark Mirror",
  "Shifting Sands",
  "The Bright Horizon",
  "Lost Legends",
  "Shadow Kingdom",
  "Ancient Prophecy",
  "Crimson Blade",
  "Echoing Silence",
  "Stormbound",
  "The Obsidian Path",
  "Fallen Stars",
  "Winds of Change",
  "The Sapphire Gate",
  "Silent Echo",
  "The Hidden Flame",
  "Silver Kingdom",
  "The Burning Crown",
  "Winter Tide",
  "Scarlet Moon",
  "Glass Kingdom",
  "Lost Horizon",
  "Ancient Skies",
  "The Velvet Crown",
  "Emerald Dreams",
  "Frozen Kingdom",
  "Secret Empire",
  "The Final Chapter",
  "The Crimson Path",
  "Storm of Ash",
  "Midnight Sun",
  "Hidden World",
  "The Silver Tide",
  "Golden Storm",
  "Echoes of Fire",
  "The Last Secret",
  "Burning Skies",
  "Shadow of Kings",
  "Ancient Flame",
  "The Lost Crown",
  "Storm of Steel",
  "Silent Kingdom",
  "Crystal Empire",
  "Dark Fire",
  "The Final Empire",
];

const bookAuthors = [
  "Andrew Walker",
  "Laura Bennett",
  "Christopher Hughes",
  "Daniel Carter",
  "Emily Collins",
  "Frank Parker",
  "Grace Reed",
  "Hannah Morgan",
  "Isaac Stewart",
  "Jacob Cooper",
  "Katherine Bailey",
  "Liam Richardson",
  "Michael Cox",
  "Natalie Howard",
  "Oliver Ward",
  "Patricia Torres",
  "Quentin Peterson",
  "Rachel Gray",
  "Samuel Ramirez",
  "Thomas James",
  "Ursula Watson",
  "Victoria Brooks",
  "William Kelly",
  "Xavier Sanders",
  "Yvonne Price",
  "Zachary Bennett",
  "Aaron Foster",
  "Brandon Powell",
  "Charlotte Long",
  "David Patterson",
  "Emma Hughes",
  "Felix Flores",
  "Gabriel Washington",
  "Hailey Butler",
  "Ian Simmons",
  "Julia Foster",
  "Kevin Gonzales",
  "Lauren Bryant",
  "Matthew Alexander",
  "Nicole Russell",
  "Oscar Griffin",
  "Paula Diaz",
  "Quincy Hayes",
  "Ryan Myers",
  "Sophia Ford",
  "Tyler Hamilton",
  "Uma Graham",
  "Victor Sullivan",
  "Wesley Wallace",
  "Ximena Woods",
  "Yasmin Cole",
  "Zane West",
  "Adrian Jordan",
  "Brianna Owens",
  "Caleb Reynolds",
  "Diana Fisher",
  "Ethan Ellis",
  "Faith Harrison",
  "George Gibson",
  "Holly McDonald",
  "Isabella Cruz",
  "Jonathan Marshall",
  "Kylie Ortiz",
  "Lucas Gomez",
  "Madison Murray",
  "Nathan Freeman",
  "Olivia Wells",
  "Patrick Webb",
  "Quinn Simpson",
  "Robert Stevens",
  "Samantha Tucker",
  "Trevor Porter",
  "Uriel Hunter",
  "Vanessa Hicks",
  "Walter Crawford",
  "Xander Henry",
  "Yara Boyd",
  "Zion Mason",
  "Alicia Morales",
  "Benjamin Kennedy",
  "Chloe Warren",
  "Derek Dixon",
  "Elena Ramos",
  "Frederick Burns",
  "Gavin Gordon",
  "Hailey Shaw",
  "Ian Holmes",
  "Jessica Rice",
  "Kyle Robertson",
  "Lily Hunt",
  "Marcus Black",
  "Natalie Daniels",
  "Owen Palmer",
  "Penelope Mills",
  "Quinton Nichols",
  "Rebecca Grant",
  "Steven Knight",
  "Taylor Ferguson",
  "Ulric Stone",
  "Victoria Hawkins",
];

const bookGenres = [
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
  "Fantasy",
  "Mystery",
  "Sci-Fi",
  "Romance",
  "Thriller",
];

const bookQuantity = [
  12, 8, 5, 2, 14, 7, 3, 6, 11, 9, 15, 13, 4, 16, 10, 19, 3, 17, 2, 21, 8, 14,
  6, 9, 12, 7, 11, 5, 3, 10, 13, 4, 2, 1, 3, 17, 8, 3, 6, 9, 12, 7, 11, 5, 18,
  10, 13, 4, 16, 20, 3, 17, 8, 14, 6, 9, 12, 7, 11, 5, 18, 10, 13, 4, 16, 20, 3,
  1, 8, 14, 6, 9, 12, 7, 11, 5, 18, 10, 1, 4, 16, 20, 3, 17, 8, 14, 6, 9, 12, 7,
  11, 5, 2, 2, 13, 4, 16, 20, 3, 17,
];
